source "https://rubygems.org"

group :test do
  gem 'rake', '~> 12.0'
  gem 'puppet', ENV['PUPPET_VERSION'] || '~> 3.8'
  gem 'puppet-lint', '~> 2.0'
  gem 'rspec-puppet', '~> 2.5'
  gem 'puppet-syntax', '~> 2.2'
  gem 'puppetlabs_spec_helper', '~> 1.2'
  gem 'metadata-json-lint', '~> 1.0'
  gem 'rspec-puppet-facts', '~> 1.7'
  gem 'deep_merge', '~> 1.1'
  gem 'danger', '~> 4.0'
  gem 'json', '~> 2.0'
  gem 'librarian-puppet', '~> 2.2'
end

group :integration do
  gem 'kitchen-docker', '~> 2.6'
  gem 'kitchen-puppet', '~> 1.47'
  gem 'kitchen-inspec', '~> 0.17'
  gem 'concurrent-ruby', '~> 0.9'
end
